### ISSUE TITLE
Command-line usage doesn't appear to be linked from anywhere on metanorma.org

### ISSUE THREAD

**Issue by scouten-adobe** [metanorma/metanorma.org#724]
Total newbie here. This tool looks like it could be quite useful to an upcoming effort, so I hope this perspective is helpful.

I spent a good chunk of time installing metanorma (thanks for the Mac Homebrew package 😘), a little bit starting to write my first Metanorma-targeted .adoc file, and then I wanted to see how it looked in HTML.

I spent a good 10-20 minutes clicking through metanorma.org and everything I could find titled "Getting Started" and could not find the basics. Eventually I did find [Metanorma usage](https://www.metanorma.org/install/usage/), but that was _only_ because I was on my way to your GitHub repo to file this issue and found the link here: https://github.com/metanorma/metanorma#usage.

I think the navigation on the Install and Getting Started sections of your site could use more detailed review to hold new users' hands through the first-time experience.

**Comment by ronaldtse** [comment]
@scouten-adobe thank you for the issue and apologies for taking so long to get back to you!

We have recently revamped our site structure, so now there is a "Learn" section as contributed from the Google Season of Docs work. Would you mind having a look to see if it better suits the needs of a "newbie" (since you're no longer one!)?

Thank you again for supporting the Metanorma project!
